ASSOCIATIONS RoR
Rocio01/Private-Events pull request #4
Opened 2020-12-07 21:06 UTC by Rocio01

Greetings
This a pull request for the project Associations(RoR) We built a site similar to a private Eventbrite which allows users to create events.
Kind  Regards

2020-12-07 23:08 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this project. Your test suites are working well and your code base is clean. :+1: 
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] I ran into series of challenges while trying to run your project on my PC. 
- The first was about your Ruby version. In your `.ruby-version` file, you specified 2.7.1 while in your gemfile, you specified 2.7.2. Use a consistent ruby version.
- The second challenge has to do with one of your gems (WDM). You should know that this gem is useful on Windows platform. As a result, you should try to include the necessary conditions on how to ignore the gem for other platforms (Linux, etc). [This SOF thread](https://stackoverflow.com/questions/16232960/guard-wont-load-wdm) might help. Here's the error message:
![23-34-32](https://user-images.githubusercontent.com/26856491/101413700-ff308180-38e4-11eb-8618-3514f02b751a.png)

- [ ] The user's show page should display events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- Right now on your app, a logged in user can see `created events` and `attended events`. However, these 2 categories of events should be sub-divided into past and upcoming events.

- [ ] Everything connected with data processing should be encapsulated in models and used in controllers.  
- i.e. no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...).
- Check my comments below for details.

- [ ] Files not related to the project should be completely removed and added to .gitignore. Delete the `.browserslistrc` and add it to your `.gitignore` file.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-12-07 23:08 UTC, teekaytech commented on app/views/events/_form.html.erb
> +  <% end %>
There should be no application logic in your views. 
Views are only for displaying information that became available to it from its corresponding controller not generating it.

The following resources might help:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-12-07 23:08 UTC, teekaytech commented on app/views/users/show.html.erb
> +    <% current_user.events.each do |event| %>
This data fetching `current_user.events` should be called in your `users_controller#show`, just like the way you did it in your `events_controller#index action.

2020-12-07 23:08 UTC, teekaytech commented on app/views/users/show.html.erb
> +    <% @user.attended_events.each do |event| %>
This also needs to be refactored. Fetch the data from the controller.

2020-12-09 18:03 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @karthykarthick and @Rocio01, Great job! 👏  Both of you have done well on this project. Amazing improvement from the last review.

However, there are still some changes that are necessary for this project to be approved.

Kindly take a look at these view files with logic in them:
- events/_form.html.erb
- events/index.html.erb
- layouts/application.html.erb
- users/_form.html.erb
- users/show.html.erb

As the last reviewer pointed out, there should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.  **The Resources below could be of immense help**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [ ] Currently, a user can modify and delete an event he/she did not create. Kindly fix this and make sure you can only modify or delete an event you created.

- [ ] For some reasons, I can not attend upcoming events, Kindly fix this as well.

- [ ] Currently, a user can attend an event as much time as he clicks attend the event. You should be able to attend an event just once.
<img width="309" alt="Screen Shot 2020-12-09 at 6 55 23 PM" src="https://user-images.githubusercontent.com/5264771/101668106-6f0f4b00-3a50-11eb-84d5-6324e0492b14.png">


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-09 20:21 UTC, blackpintz requested changes
# Status: Changes Required 🤓

## Hello team 😄,

**Great job implementing the requested changes. However, there are still a few fixes required.**

1). **Your views folder still has logic in form of conditional statements and loops. View-related logic can be encapsulated in `View helpers (app/helpers/*_helper.rb)` and not `partial templates` as you have done. Hint: You can check [this](https://guides.rubyonrails.org/v5.0/layouts_and_rendering.html) guideline on how to use rendering collections for loops. The view files with logic include:**

- all the partial templates in the `events` directory.
- `layouts/_header.html.erb`.
- `users/_show.html.erb`.

2). **I will use an example. Jen has created an event for Dec 13th. When Ken clicks to attend the event, it doesn't show on his list of upcoming events on his profile page. Also, Jen created another event for Dec 1st, when Ken clicks to attend, it doesn't show on his list of previous events.**

3).**As mentioned by the previous TSE, fix attend event button so the user is not able to click it more than once.**

4). **You have a failing RSpec test.**
![rspec](https://user-images.githubusercontent.com/38922385/101682637-f2429800-3a74-11eb-975d-2f18fea35475.png)

5). **Fix the linter errors.**


## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-09 20:21 UTC, ghost commented on app/views/users/_form.html.erb
> +<% end %>
I can't find where you have referenced this partial. Delete it since it is of no use.

2020-12-11 17:28 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello Team!

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

#### Kindly take a look at these view files, you still have logic in them:
- events/index.html.erb
- layouts/application.html.erb
- users/show.html.erb

There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.  **The Resources below could be of immense help**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [x] Kindly add outline/border to your input fields as it's really hard to know where to type. 
<img width="513" alt="Screen Shot 2020-12-11 at 5 40 23 PM" src="https://user-images.githubusercontent.com/5264771/101932515-2cc64500-3bdb-11eb-84e4-d8d1bb19d674.png">
<img width="536" alt="Screen Shot 2020-12-11 at 6 04 47 PM" src="https://user-images.githubusercontent.com/5264771/101932666-65feb500-3bdb-11eb-9c78-0fcbbda5b558.png">

- [x] Good test coverage, just remove all pending examples 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-11 21:58 UTC, Rocio01 commented
Greetings
 We face a problem with the logic in the views because they have many html code in the html.erb files inside the logic and we can't find a way to translate that in the helper methods.
Thanks for the attention
Kind regards
An example 
![ejemplo](https://user-images.githubusercontent.com/57466928/101958554-8fb2de80-3bd1-11eb-974e-2ce3dd10d424.PNG)

2020-12-12 00:30 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below: 
 
## [REQUIRED CHANGES]
- [ ] Please don't use inline styling;
- [ ] You should only show the events if the user has logged in;
Currenly this is your homepage:
![image](https://user-images.githubusercontent.com/56762529/101966701-8177b900-3bf7-11eb-986b-fbd1d2af2d0f.png)
- [ ] When we click on show event, it throws an reference error, please fix it;
- [ ] You have to validate the input data!! currently users can type text on date fields! ⚠
![image](https://user-images.githubusercontent.com/56762529/101966784-e03d3280-3bf7-11eb-8e52-322129e94dfa.png)
- [ ] We have rspec errors, please fix them;

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-12-12 00:30 UTC, kevincappuccino commented on app/views/events/index.html.erb
> +        <div class="card-body">
❌ Please remove inline styling;

2020-12-12 00:30 UTC, kevincappuccino commented on app/views/events/index.html.erb
> +        <div class="card-body">
❌ Please remove inline styling;

2020-12-12 00:30 UTC, kevincappuccino commented on app/views/events/show.html.erb
> +        <div class="card-body">
❌ Please remove inline styling;

2020-12-12 00:30 UTC, kevincappuccino commented on app/views/events/show.html.erb
> +        <div class="card-body">
❌ Please remove inline styling;

2020-12-14 21:09 UTC, Rocio01 commented
Greetings
Thanks for the review
On the original Eventbrite page you can see the event even if you are not logged in, so we added a home page, but you can still view the events without logging in. Only attend when you are logged in.
Kind regards.

2020-12-15 03:18 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Zulma Rocio Martinez Guarin & Karthick Harimoorthy** 
Nice job so far :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
Still, there is some improvement to do in your tests before you can go ahead:

- [ ] Complete pending tests or remove them
- [ ] In your tests, each scenario should only have one expect
- [ ] Remove commented code from the files in spec/helpers folder
- [ ] Remove commented code in event_attendence_spec.rb file
- [ ] Remove spec files with no tests
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-12-15 16:48 UTC, Temmarie requested changes
## Changes Required! :recycle:
### Hi @Rocio01 and @karthykarthick ! 👍 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] Delete empty test files.

- [ ] FIx the errors in your test files.

![Screenshot (156)](https://user-images.githubusercontent.com/49621279/102244917-36aeb780-3efd-11eb-9959-c2a28c90374b.png)



__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-12-15 18:04 UTC, Rocio01 commented
Greetings
Thank you for your revision, but on our computers, we don't get errors in the test files.
Kind regards
![spec](https://user-images.githubusercontent.com/57466928/102253982-0ef82900-3ed6-11eb-9cc3-04829acd45fb.PNG)

2020-12-15 18:43 UTC, javitocor approved these changes
# STATUS APPROVED 🥇 

Hello team! ✋ 
Your project meets all the basic requirements! ⭐ 
Congratulations! 🥳  It has been approved! 👍 
Remember to fill up the completion form 📑 , merge it and you can move into the next project 🚀 
Good luck with it! 😺

2020-12-15 19:07 UTC, merged